### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by bird-c** [yajra/laravel-address#1]
Hi Sir, 

I tried to integrate this on my project with Laravel 8 and I got error when installing the package

![image](https://user-images.githubusercontent.com/69282512/100404744-14afdb00-309d-11eb-8fd3-a8458b46a053.png)

Thank you in advance

- Operating System : macOS Catalina with Laravel Homestead
- PHP Version 7.4
- Laravel Version 8.14

**Comment by krutsednar** [comment]
up for this

**Comment by yajra** [comment]
Released v0.4.0 which allows Laravel 8 installations. Not tested but I think the package would still work. Thanks!
