### ISSUE TITLE
Laravel 9 Compatibility

### ISSUE THREAD

**Issue by jvbalcita** [yajra/laravel-address#10]
It's not working on Laravel 9 upgrade process.

**Comment by acxgray** [comment]
+1 is there any other way to make laravel-address works when upgrading to Laravel 9. Thanks in advance

**Comment by anonymouse703** [comment]
@jvbalcita  any update?

**Comment by yajra** [comment]
I'm not using the package atm. Will add L9 in composer.json for this to be installable. Feel free to submit a PR if you found an issue. Thanks!
