### ISSUE TITLE
Feature request for the latest PSGC 

### ISSUE THREAD

**Issue by akiraaisha** [yajra/laravel-address#19]
### Feature request to be added:

- 10-Digit PSGC
- Correspondence Code

### Optional
- Income Classification
- Urban/Rural

> [As of Q1-2024 Publication Datafile of PSGC](https://psa.gov.ph/system/files/scd/PSGC-1Q-2024-Publication-Datafile_0.xlsx)

**Comment by yajra** [comment]
Thanks for the heads up on the new 10 digit structure. Will try to support this when I got the chance.
