### ISSUE TITLE
AddressSeeder not working

### ISSUE THREAD

**Issue by kennethsantianez** [yajra/laravel-address#5]
I encountered an error when I try to execute command: 
`php artisan db:seed --class=\\AddressSeeder`

This is the error message
`Target class [\\AddressSeeder] does not exist`

### System details

- Operating System: Windows
- PHP Version : 7.4
- Laravel Version : 8
- laravel-address Version: 0.6.1

**Comment by kennethsantianez** [comment]
For Laravel Framework 8.36 , this is what I did temporarily to make it work @yajra 

- Add `namespace Database\Seeders;` at the top of `AddressSeeder.php`
- Execute `composer dump-autoload`
- Execute `php artisan db:seed --class=AddressSeeder` instead of `php artisan db:seed --class=\\AddressSeeder`

![image](https://user-images.githubusercontent.com/62993231/117840059-64323e00-b2ae-11eb-879e-c5154e4ef2b3.png)

The solution is not the right way since I modified the vendor source code.

**Comment by yajra** [comment]
Works fine for me? 

```sh
art db:seed \\AddressSeeder                                                                                                                                                                                                 Parsing PSA official PSGC publication (/Users/yajra/www/xxx/vendor/yajra/laravel-address/database/seeds/publication/PSGC_Publication_Dec2020.xlsx).
```

Another way is call it in the db class seeder.

```php
use AddressSeeder;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        $this->call(AddressSeeder::class);
...
```

**Comment by kennethsantianez** [comment]
@yajra , Calling it in the db class seeder works . Thank you!
