### ISSUE TITLE
How can I change table names?

### ISSUE THREAD

**Issue by jonjieviduya** [yajra/laravel-address#6]
I currently have `provinces` table exists in my database so maybe we can have an option for the config file to change the table name?

**Comment by yajra** [comment]
I think this is not yet supported. 

But you can try overriding the base models and manually set the table property. I guess it might work but haven't tried yet.

**Comment by yajra** [comment]
To add, you would also need to publish and update the migration file. Seeder file might need an update too.

**Comment by yajra** [comment]
No plans to support atm. Thanks!
