### ISSUE TITLE
Unable to call API Cities by Region

### ISSUE THREAD

**Issue by jvbalcita** [yajra/laravel-address#8]
Hi @yajra,

Is there a way I can call the cities api by region_id? or just call the all the cities. I can't seem to make it work with the instructions maybe I'm just making it complicated but I hope you can help me. 

Thank you in advance!

**Comment by yajra** [comment]
You can use the CitiesRepository to get by region id. See https://github.com/yajra/laravel-address/blob/master/src/Repositories/Cities/CitiesRepository.php#L32

**Comment by jvbalcita** [comment]
Thank you for this @yajra , I end up using the province to get the cities. I just saw one issue. when a region is selected regardless if NCR or any other region the result of province is the same, it's pulling all the provinces.
