### ISSUE TITLE
Unable to get some barangays in some Cities.

### ISSUE THREAD

**Issue by bryanjamesdelaluya** [yajra/laravel-address#9]
I can't get list of Barangays in Region IV-A Calabarzon > Laguna > City of San Pablo > No results. But upon checking the database, there are list of barangays for San Pablo.

**Comment by yajra** [comment]
I'm not using the package atm and may not be able to support this. Please do not hesitate to submit a PR for a possible fix. Thanks!

**Comment by yajra** [comment]
You can use this route: `api/address/barangays/012802`

Where `012802` is the city_id.

01 = Region ID 
0128 = Province ID
012802 = City ID

That's the pattern for IDs. Thanks!
